sudo: required

services:
   - docker

env:
  global:
     - secure: "aRxEKBXnGy2PWEYtjVX9wBKFIsX738w44/h+8cJX8Tqr5dUNuJ5SzXqvavjrM8guTi8GMh1DgtTcwYIlc+RbjQ1U6ynFeP4BBveYMhyI/18A4EZsIFjcAQ9oaoqLBl8YR77Lk7GVEEohvRjfbdNfnyldjRQe5rSuI2c7s/xlQAk="

  matrix:
     - VIOLETLAND_TARGET='windows-amd64-gcc'

before-install:
  - sudo npm install -g mini-cross

script:
  - ./deploy/travis-ci/$VIOLETLAND_TARGET/script.sh
  - #(cd deploy/docker && make $VIOLETLAND_TARGET)

after_success:
 - #./deploy/travis-ci/$TARGET/after-success.sh
